#!/usr/bin/env bash
# edit the /etc/hosts file to change the IP address of localhost to

cp /etc/hosts /etc/hosts.bak

sed -i '/localhost/d' /etc/hosts
sed -i '/facebook.com/d' /etc/hosts

echo "127.0.0.2   localhost" >> /etc/hosts
echo "8.8.8.8     facebook.com" >> /etc/hosts
