#!/usr/bin/env bash
# edit the /etc/hosts file to change the IP address of localhost to

sudo cp /etc/hosts /etc/hosts.backup

localhost_entry="127.0.0.2 localhost"
facebook_entry="8.8.8.8 facebook.com"

sudo sed -i '/localhost/d' /etc/hosts
sudo sed -i '/facebook.com/d' /etc/hosts

echo "$localhost_entry" | sudo tee -a /etc/hosts
echo "$facebook_entry" | sudo tee -a /etc/hosts

echo "Updated /etc/hosts file:"
cat /etc/host