#!/bin/bash
# Script to change localhost and facebook.com IP resolution

sudo sed -i 's/^127\.0\.0\.1\s\+localhost/127.0.0.2\tlocalhost/' /etc/hosts

sudo sed -i '/facebook.com/d' /etc/hosts

echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts > /dev/null